name = "solarroots-coming-soon"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[assets]
directory = "public"
binding = "ASSETS"

[vars]
SITE_BASE_URL = "https://solarroots.example.com"

[[d1_databases]]
binding = "DB"
database_name = "solarroots"
database_id = "00000000-0000-0000-0000-000000000000" # replace with your D1 database UUID
